
DELETE FROM metric;
DELETE FROM metric_type;

ALTER TABLE IF EXISTS metric
    DROP COLUMN metric_type_id;

ALTER TABLE IF EXISTS metric_type
    ALTER COLUMN id DROP IDENTITY IF EXISTS;

ALTER TABLE IF EXISTS metric_type
    ALTER COLUMN id SET DATA TYPE VARCHAR(36) USING (id::VARCHAR(36)),
    DROP CONSTRAINT IF EXISTS unique_metric_type,
    ADD CONSTRAINT fk_metric_type FOREIGN KEY (id) REFERENCES metric(id) ON DELETE RESTRICT ON UPDATE CASCADE;
