
# 1. ОБНОВЛЕНИЕ ЗНАЧЕНИЯ МЕТРИКИ

# Обновление конкретной метрики типа counter
POST {{domain}}:{{port}}/update/counter/PollCount/527
Accept-Encoding: gzip

###

# Обновление конкретной метрики типа counter с внедрённым XSS
POST {{domain}}:{{port}}/update/counter/<script>alert("Hacked")</script>/527

###

# Обновление конкретной метрики типа gauge
POST {{domain}}:{{port}}/update/gauge/RandomVal/0.74
Accept-Encoding: gzip

###

# Обновление метрики типа gauge методом /update
POST {{domain}}:{{port}}/update/
Content-Type: application/json
Accept-Encoding: gzip

{
  "id": "12",
  "type": "gauge",
  "name": "RandomVal",
  "value": 0.47
}

###

# Обновление метрики типа counter без заранее заданного идентификатора методом /update
POST {{domain}}:{{port}}/update/
Content-Type: application/json
Accept-Encoding: gzip

{
  "type": "counter",
  "name": "PollCount",
  "delta": 1
}

###


# 2. ПОЛУЧЕНИЕ ЗНАЧЕНИЯ МЕТРИКИ

# Получение значения метрики типа counter
GET {{domain}}:{{port}}/value/counter/PollCount

###

# Получение значения метрики типа gauge
GET {{domain}}:{{port}}/value/gauge/RandomVal

###

# Получение несуществующего значения метрики типа counter
GET {{domain}}:{{port}}/value/counter/test

###

# Получение метрики типа gauge методом /value
POST {{domain}}:{{port}}/value/
Content-Type: application/json
Accept-Encoding: gzip

{
  "id": "12",
  "type": "gauge"
}

###

# Получение метрики типа counter методом /value
#
# Идентификатор необходимо корректировать
#  - Использовать запрос / для проверки ID;
#  - Либо вызывать метод internal/server/request/server.http:32 первым.
POST {{domain}}:{{port}}/value/
Content-Type: application/json
Accept-Encoding: gzip

{
  "id": "0",
  "type": "counter"
}

###


# 3. ПОЛУЧЕНИЕ СПИСКА МЕТРИК

# Получение списка метрик из хранилища
GET {{domain}}:{{port}}/
Accept-Encoding: gzip

###
