
# 1. ОБНОВЛЕНИЕ ЗНАЧЕНИЯ МЕТРИКИ

# Обновление конкретной метрики типа counter
POST {{domain}}:{{port}}/update/counter/PollCount/527
Accept-Encoding: gzip

###

# Обновление конкретной метрики типа counter с внедрённым XSS
POST {{domain}}:{{port}}/update/counter/<script>alert("Hacked")</script>/527

###

# Обновление конкретной метрики типа gauge
POST {{domain}}:{{port}}/update/gauge/RandomVal/0.74
Accept-Encoding: gzip

###

# Обновление метрики типа gauge методом /update
POST {{domain}}:{{port}}/update/
Content-Type: application/json
Accept-Encoding: gzip

{
  "id": "12",
  "type": "gauge",
  "name": "RandomVal",
  "value": 0.47
}

###

# Обновление метрики типа counter без заранее заданного идентификатора методом /update
POST {{domain}}:{{port}}/update/
Content-Type: application/json
Accept-Encoding: gzip

{
  "type": "counter",
  "name": "PollCount",
  "delta": 1
}

###

# Обновление пачкм метрик /updates
POST {{domain}}:{{port}}/updates/
Content-Type: application/json
Accept-Encoding: gzip

[
  {
    "type": "gauge",
    "name": "TestGauge",
    "value": 0.97
  },
  {
    "type": "counter",
    "name": "TestCounter",
    "delta": 1
  }
]

###

# Обновление пачкм метрик /updates. Реальный запрос
POST {{domain}}:{{port}}/updates/
Content-Type: application/json
Accept-Encoding: gzip

[
  {
    "type": "gauge",
    "name": "Alloc",
    "value": 2214784
  },
  {
    "type": "gauge",
    "name": "BuckHashSys",
    "value": 10102
  },
  {
    "type": "gauge",
    "name": "Frees",
    "value": 227
  },
  {
    "type": "gauge",
    "name": "GCCPUFraction",
    "value": 0
  },
  {
    "type": "gauge",
    "name": "GCSys",
    "value": 1872520
  },
  {
    "type": "gauge",
    "name": "HeapAlloc",
    "value": 2214784
  },
  {
    "type": "gauge",
    "name": "HeapIdle",
    "value": 753664
  },
  {
    "type": "gauge",
    "name": "HeapInuse",
    "value": 3153920
  },
  {
    "type": "gauge",
    "name": "HeapObjects",
    "value": 3115
  },
  {
    "type": "gauge",
    "name": "HeapReleased",
    "value": 753664
  },
  {
    "type": "gauge",
    "name": "HeapSys",
    "value": 3907584
  },
  {
    "type": "gauge",
    "name": "LastGC",
    "value": 0
  },
  {
    "type": "gauge",
    "name": "Lookups",
    "value": 0
  },
  {
    "type": "gauge",
    "name": "MCacheInuse",
    "value": 14016
  },
  {
    "type": "gauge",
    "name": "MCacheSys",
    "value": 16352
  },
  {
    "type": "gauge",
    "name": "MSpanInuse",
    "value": 55200
  },
  {
    "type": "gauge",
    "name": "MSpanSys",
    "value": 65280
  },
  {
    "type": "gauge",
    "name": "Mallocs",
    "value": 3342
  },
  {
    "type": "gauge",
    "name": "NextGC",
    "value": 4194304
  },
  {
    "type": "gauge",
    "name": "NumForcedGC",
    "value": 0
  },
  {
    "type": "gauge",
    "name": "NumGC",
    "value": 0
  },
  {
    "type": "gauge",
    "name": "OtherSys",
    "value": 964386
  },
  {
    "type": "gauge",
    "name": "PauseTotalNs",
    "value": 0
  },
  {
    "type": "gauge",
    "name": "StackInuse",
    "value": 262144
  },
  {
    "type": "gauge",
    "name": "StackSys",
    "value": 262144
  },
  {
    "type": "gauge",
    "name": "Sys",
    "value": 7098368
  },
  {
    "type": "gauge",
    "name": "TotalAlloc",
    "value": 2214784
  },
  {
    "type": "gauge",
    "name": "RandomValue",
    "value": 0.3834050811587329
  },
  {
    "type": "counter",
    "name": "PollCount",
    "delta": 1
  }
]

###


# 2. ПОЛУЧЕНИЕ ЗНАЧЕНИЯ МЕТРИКИ

# Получение значения метрики типа counter
GET {{domain}}:{{port}}/value/counter/PollCount

###

# Получение значения метрики типа gauge
GET {{domain}}:{{port}}/value/gauge/RandomVal

###

# Получение несуществующего значения метрики типа counter
GET {{domain}}:{{port}}/value/counter/test

###

# Получение метрики типа gauge методом /value
POST {{domain}}:{{port}}/value/
Content-Type: application/json
Accept-Encoding: gzip

{
  "id": "12",
  "type": "gauge"
}

###

# Получение метрики типа gauge методом /value
POST {{domain}}:{{port}}/value/
Content-Type: text/plain
Accept-Encoding: gzip
Content-Encoding: gzip

H4sIAAAAAAAAA6tWykxRslIyNFLSUSqpLEgFstMTS9NTlWoBLLcKjRoAAAA=

###

# Получение метрики типа counter методом /value
#
# Идентификатор необходимо корректировать
#  - Использовать запрос / для проверки ID;
#  - Либо вызывать метод internal/server/request/server.http:32 первым.
POST {{domain}}:{{port}}/value/
Content-Type: application/json
Accept-Encoding: gzip

{
  "id": "0",
  "type": "counter"
}

###


# 3. ПОЛУЧЕНИЕ СПИСКА МЕТРИК

# Получение списка метрик из хранилища
GET {{domain}}:{{port}}/
Accept-Encoding: gzip

###


# 4. БАЗА ДАННЫХ

# Получение списка метрик из хранилища
GET {{domain}}:{{port}}/ping

###
