
# 1. ОБНОВЛЕНИЕ ЗНАЧЕНИЯ МЕТРИКИ

# Обновление конкретной метрики типа counter
POST {{domain}}:{{port}}/update/counter/PollCount/527
Accept-Encoding: gzip

###

# Обновление конкретной метрики типа counter с внедрённым XSS
POST {{domain}}:{{port}}/update/counter/<script>alert("Hacked")</script>/527

###

# Обновление конкретной метрики типа gauge
POST {{domain}}:{{port}}/update/gauge/RandomVal/0.74
Accept-Encoding: gzip

###

# Обновление метрики типа gauge методом /update
POST {{domain}}:{{port}}/update/
Content-Type: application/json
Accept-Encoding: gzip

{
  "id": "RandomValue",
  "type": "gauge",
  "value": 0.47
}

###

# Обновление метрики типа counter без заранее заданного идентификатора методом /update
POST {{domain}}:{{port}}/update/
Content-Type: application/json
Accept-Encoding: gzip

{
  "id": "PollCount",
  "type": "counter",
  "delta": 1
}

###

# Обновление пачкм метрик /updates
POST {{domain}}:{{port}}/updates/
Content-Type: application/json
Accept-Encoding: gzip

[
  {
    "id": "GaugeMetric",
    "type": "gauge",
    "value": 0.97
  },
  {
    "id": "CounterMetric",
    "type": "counter",
    "delta": 1
  }
]

###

# Обновление пачкм метрик /updates. Реальный запрос
POST {{domain}}:{{port}}/updates/
Content-Type: application/json
Accept-Encoding: gzip

[
  {
    "id": "Alloc",
    "type": "gauge",
    "value": 2214784
  },
  {
    "id": "BuckHashSys",
    "type": "gauge",
    "value": 10102
  },
  {
    "id": "Frees",
    "type": "gauge",
    "value": 227
  },
  {
    "id": "GCCPUFraction",
    "type": "gauge",
    "value": 0
  },
  {
    "id": "GCSys",
    "type": "gauge",
    "value": 1872520
  },
  {
    "id": "HeapAlloc",
    "type": "gauge",
    "value": 2214784
  },
  {
    "id": "HeapIdle",
    "type": "gauge",
    "value": 753664
  },
  {
    "id": "HeapInuse",
    "type": "gauge",
    "value": 3153920
  },
  {
    "id": "HeapObjects",
    "type": "gauge",
    "value": 3115
  },
  {
    "id": "HeapReleased",
    "type": "gauge",
    "value": 753664
  },
  {
    "id": "HeapSys",
    "type": "gauge",
    "value": 3907584
  },
  {
    "id": "LastGC",
    "type": "gauge",
    "value": 0
  },
  {
    "id": "Lookups",
    "type": "gauge",
    "value": 0
  },
  {
    "id": "MCacheInuse",
    "type": "gauge",
    "value": 14016
  },
  {
    "id": "MCacheSys",
    "type": "gauge",
    "value": 16352
  },
  {
    "id": "MSpanInuse",
    "type": "gauge",
    "value": 55200
  },
  {
    "id": "MSpanSys",
    "type": "gauge",
    "value": 65280
  },
  {
    "id": "Mallocs",
    "type": "gauge",
    "value": 3342
  },
  {
    "id": "NextGC",
    "type": "gauge",
    "value": 4194304
  },
  {
    "id": "NumForcedGC",
    "type": "gauge",
    "value": 0
  },
  {
    "id": "NumGC",
    "type": "gauge",
    "value": 0
  },
  {
    "id": "OtherSys",
    "type": "gauge",
    "value": 964386
  },
  {
    "id": "PauseTotalNs",
    "type": "gauge",
    "value": 0
  },
  {
    "id": "StackInuse",
    "type": "gauge",
    "value": 262144
  },
  {
    "id": "StackSys",
    "type": "gauge",
    "value": 262144
  },
  {
    "id": "Sys",
    "type": "gauge",
    "value": 7098368
  },
  {
    "id": "TotalAlloc",
    "type": "gauge",
    "value": 2214784
  },
  {
    "id": "RandomValue",
    "type": "gauge",
    "value": 0.3834050811587329
  },
  {
    "id": "PollCount",
    "type": "counter",
    "delta": 1
  },
  {
    "id": "PollCount",
    "type": "counter",
    "delta": 1
  }
]

###


# 2. ПОЛУЧЕНИЕ ЗНАЧЕНИЯ МЕТРИКИ

# Получение значения метрики типа counter
GET {{domain}}:{{port}}/value/counter/PollCount

###

# Получение значения метрики типа gauge
GET {{domain}}:{{port}}/value/gauge/RandomVal

###

# Получение несуществующего значения метрики типа counter
GET {{domain}}:{{port}}/value/counter/test

###

# Получение метрики типа gauge методом /value
POST {{domain}}:{{port}}/value/
Content-Type: application/json
Accept-Encoding: gzip

{
  "id": "RandomValue",
  "type": "gauge"
}

###

# Получение метрики типа gauge методом /value
POST {{domain}}:{{port}}/value/
Content-Type: text/plain
Accept-Encoding: gzip
Content-Encoding: gzip

H4sIAAAAAAAAA6tWykxRslIyNFLSUSqpLEgFstMTS9NTlWoBLLcKjRoAAAA=

###

# Получение метрики типа counter методом /value
POST {{domain}}:{{port}}/value/
Content-Type: application/json
Accept-Encoding: gzip

{
  "id": "PollCount",
  "type": "counter"
}

###


# 3. ПОЛУЧЕНИЕ СПИСКА МЕТРИК

# Получение списка метрик из хранилища
GET {{domain}}:{{port}}/
Accept-Encoding: gzip

###


# 4. БАЗА ДАННЫХ

# Получение списка метрик из хранилища
GET {{domain}}:{{port}}/ping

###
